### ISSUE TITLE
`riscv-rt`: Using this as a library?

### ISSUE THREAD

**Issue by hyperswine** [rust-embedded/riscv#154]
Is it possible to use this as a "just works" library without extra copying/config or is it meant to be used as a template?

**Comment by romancardenas** [comment]
I'm closing this issue as stale, as I believe the problem was that the linker arguments were not provided. Feel free to re-open it if you consider it necessary.

**Comment by xobs** [comment]
I believe this issue should be reopened.

There is a directory called `examples`, and if you use the examples they don't work and produce the error mentioned.

The examples should be fixed so that they work, and documentation should be added on how to use it.

Neither [the project's README.md](https://github.com/rust-embedded/riscv/blob/master/riscv-rt/README.md) nor the [docs.rs documentation](https://docs.rs/crate/riscv-rt/latest) give any indication on what is needed.

**Comment by romancardenas** [comment]
I'm currently under very tight deadlines and won't be able to work on this. I will try to get back ASAP.
